from __future__ import annotations

import numpy as np

from .models import PointCloud


PLY_VERTEX_DTYPE = np.dtype(
    [
        ("x", "<f4"),
        ("y", "<f4"),
        ("z", "<f4"),
        ("red", "u1"),
        ("green", "u1"),
        ("blue", "u1"),
    ]
)


def encode_binary_ply(cloud: PointCloud) -> bytes:
    count = cloud.points.shape[0]
    vertices = np.empty(count, dtype=PLY_VERTEX_DTYPE)
    vertices["x"] = cloud.points[:, 0]
    vertices["y"] = cloud.points[:, 1]
    vertices["z"] = cloud.points[:, 2]
    vertices["red"] = cloud.colors[:, 0]
    vertices["green"] = cloud.colors[:, 1]
    vertices["blue"] = cloud.colors[:, 2]

    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment Generated by RGB-D Viewer\n"
        f"element vertex {count}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n"
        "end_header\n"
    ).encode("ascii")
    return header + vertices.tobytes(order="C")
